version: "3.7"

services:
  app:
    image: "c18-102-m-php-vue:${TAG:-latest}"
    build:
      args:
        user: testusr
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: server-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - my-network

  web:
    image: nginx:1.19.4
    container_name: server-nginx
    restart: unless-stopped
    ports:
      - ${SERVER_PORT:-80}:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - my-network

  db:
    image: mysql:8.0
    container_name: server-db
    restart: unless-stopped
    ports:
      - ${SERVER_PORT_DB:-3306}:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-safe-kids}
      - MYSQL_USER=${DB_USERNAME:-safe-kids-user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  dbdata:
